import Head from 'next/head'
import Image from 'next/image'
import { ProductsData } from '../components/data/ProductsData'
import Featured from '../components/featured/Featured'
import Hero from '../components/hero/Hero'
import Products from '../components/products/Products'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Tega Food App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <Hero />
        <Products heading='Choose your favourite' data={ProductsData} />
        < Featured />
      </section>
    </div>
  )
}
